from app import app, db
from app.models import User, Person, Contact, Subject, Subscription, SubscriptionType, parent_child_table, Room, Lesson, \
    SchoolClass
from sqlalchemy.orm import class_mapper
from datetime import datetime, timedelta, time, date

app.app_context().push()


def print_table(table_model):
    try:
        all_rows = table_model.query.all()

        if not all_rows:
            print(f"No rows found in the table: {table_model.__tablename__}")
            return

        mapper = class_mapper(table_model)
        columns = [column.key for column in mapper.columns]

        print(f"Table: {table_model.__tablename__}")
        print(columns)
        for row in all_rows:
            for column in columns:
                value = getattr(row, column)
                print(value, end='\t')
            print("")

    except Exception as e:
        print(f"Error fetching data: {str(e)}")


def print_parent_child_table():
    query = db.session.query(parent_child_table)
    rows = query.all()

    for row in rows:
        print(row)


def create_student(student_info):
    last_name = student_info["student"]["last_name"]
    first_name = student_info["student"]["first_name"]
    patronym = student_info["student"]["patronym"]
    dob = datetime.strptime(student_info["student"]["dob"], '%d.%m.%Y').date() \
        if student_info["student"]["dob"] else None
    status = student_info["student"]["status"]
    pause_date = datetime.strptime(student_info["student"]["pause_until"], '%d.%m.%Y').date() \
        if student_info["student"]["pause_until"] else None
    leaving_reason = student_info["student"]["leaving_reason"]

    new_student = Person(
        last_name=last_name,
        first_name=first_name,
        patronym=patronym,
        dob=dob,
        person_type="Ребенок",
        status=status,
        pause_until=pause_date,
        leaving_reason=leaving_reason
    )

    return new_student


def create_contact(student_info, i):
    telegram = student_info["contact"][i]["telegram"]
    phone = student_info["contact"][i]["phone"]
    other_contact = student_info["contact"][i]["other_contact"]

    new_contact = Contact(
        telegram=telegram,
        phone=phone,
        other_contact=other_contact
    )

    return new_contact


def create_parent(student_info, i):
    parent_last_name = student_info["parent"][i]["last_name"]
    parent_first_name = student_info["parent"][i]["first_name"]
    parent_patronym = student_info["parent"][i]["patronym"]

    new_parent = Person(
        last_name=parent_last_name,
        first_name=parent_first_name,
        patronym=parent_patronym,
        person_type="Взрослый"
    )

    return new_parent


def handle_contact_info(student_info, student, i):
    contact_select = student_info["contact_select"][i]
    relation_type = student_info["relation"][i]

    if relation_type == "Сам ребенок":
        contact = create_contact(student_info, i)
        db.session.add(contact)
        db.session.commit()

        student.contacts.append(contact)

    else:
        if contact_select == "Выбрать":
            parent_id = int(student_info["selected_contact"][i])
            parent = Person.query.filter_by(id=parent_id).first()
            contact = Contact.query.filter_by(person_id=parent_id).first()

        else:
            contact = create_contact(student_info, i)
            parent = create_parent(student_info, i)
            db.session.add(parent)
            db.session.add(contact)
            db.session.commit()

            parent.contacts.append(contact)
            parent.primary_contact = parent.id

        student.parents.append(parent)
        assign_relation_type(student_info, student, parent, i)

    if student_info['primary_contact'] == i:
        student.primary_contact = contact.person_id
    db.session.commit()


def assign_relation_type(student_info, student, parent, i):
    relation_type = student_info["relation"][i]

    if relation_type:
        relation_entry = parent_child_table.update().where(
            (parent_child_table.c.parent_id == parent.id) &
            (parent_child_table.c.child_id == student.id)
        ).values(relation=relation_type)

        db.session.execute(relation_entry)


def add_student(student_info):
    try:
        student = create_student(student_info)
        db.session.add(student)
        db.session.commit()

        contact_count = len(student_info["contact_select"])
        for i in range(1, contact_count + 1):
            handle_contact_info(student_info, student, i)
        print('Новый ученик добавлен в систему.')

    except Exception as e:
        db.session.rollback()
        print(f'Ошибка при добавлении ученика: {str(e)}')


def delete_record(table_model, record_id):
    record = table_model.query.filter_by(id=record_id).first()
    if record:
        db.session.delete(record)
        db.session.commit()


def create_teacher(teacher_info):
    teacher_last_name = teacher_info["teacher"]["last_name"]
    teacher_first_name = teacher_info["teacher"]["first_name"]
    teacher_patronym = teacher_info["teacher"]["patronym"]

    new_teacher = Person(
        last_name=teacher_last_name,
        first_name=teacher_first_name,
        patronym=teacher_patronym,
        person_type="Взрослый",
        teacher=True
    )

    return new_teacher


def create_teacher_contact(teacher_info):
    telegram = teacher_info["contact"]["telegram"]
    phone = teacher_info["contact"]["phone"]
    other_contact = teacher_info["contact"]["other_contact"]

    new_contact = Contact(
        telegram=telegram,
        phone=phone,
        other_contact=other_contact
    )

    return new_contact


def teachers_subjects(subjects_taught, teacher):
    for subj in subjects_taught:
        new_subj = Subject.query.filter_by(name=subj).first()
        teacher.subjects_taught.append(new_subj)
        db.session.commit()


def add_teacher(teacher_info):
    try:
        teacher = create_teacher(teacher_info)
        contact = create_teacher_contact(teacher_info)
        db.session.add(teacher)
        db.session.add(contact)
        db.session.commit()

        teacher.contacts.append(contact)
        teacher.primary_contact = teacher.id
        db.session.commit()
        if teacher_info["subjects"]:
            teachers_subjects(teacher_info["subjects"], teacher)

        print('Новый учитель добавлен в систему.')

    except Exception as e:
        db.session.rollback()
        print(f'Ошибка при добавлении учителя: {str(e)}')


def add_subject(subject):
    try:
        subject_name = subject["name"]
        subject_short_name = subject["short_name"]
        one_time_price = subject["one_time_price"]

        new_subject = Subject(
            name=subject_name,
            short_name=subject_short_name,
            one_time_price=one_time_price
        )

        db.session.add(new_subject)
        db.session.commit()

        print('Новое занятие добавлено в систему.')

    except Exception as e:
        db.session.rollback()
        print(f'Ошибка при добавлении занятия: {str(e)}')


def add_person(person):
    try:
        last_name = person["last_name"]
        first_name = person["first_name"]
        patronym = person["patronym"]
        dob = datetime.strptime(person["dob"], '%d.%m.%Y').date() if person["dob"] else None
        person_type = person["person_type"]
        status = person["status"]
        teacher = person["teacher"]
        pause_date = datetime.strptime(person["pause_until"], '%d.%m.%Y').date() if person["pause_until"] else None
        leaving_reason = person["leaving_reason"]

        new_person = Person(
            last_name=last_name,
            first_name=first_name,
            patronym=patronym,
            dob=dob,
            person_type=person_type,
            status=status,
            teacher=teacher,
            pause_until=pause_date,
            leaving_reason=leaving_reason
        )
        db.session.add(new_person)
        db.session.commit()

        print('Человек добавлен в систему.')

    except Exception as e:
        db.session.rollback()
        print(f'Ошибка при добавлении человека: {str(e)}')


def create_subscription(student_id, subject_id, subscription_type_id, lessons=8):
    try:
        new_subscription = Subscription(
            subject_id=subject_id,
            student_id=student_id,
            subscription_type_id=subscription_type_id,
            lessons_left=lessons
        )

        db.session.add(new_subscription)
        db.session.commit()

        print('Новый абонемент добавлен в систему.')

    except Exception as e:
        db.session.rollback()
        print(f'Ошибка при добавлении абонемента: {str(e)}')


def create_lesson(lesson_info):
    lesson_date = datetime.strptime(lesson_info['date'], '%d.%m.%Y').date()
    start_time = datetime.strptime(lesson_info['start_time'], '%H:%M').time()
    end_time = datetime.strptime(lesson_info['end_time'], '%H:%M').time()
    lesson_type = lesson_info['lesson_type']
    subject_id = lesson_info['subject_id']
    room_id = lesson_info['room_id']
    teacher_id = lesson_info['teacher_id']

    lesson = Lesson(
        date=lesson_date,
        start_time=start_time,
        end_time=end_time,
        lesson_type=lesson_type,
        room_id=room_id,
        subject_id=subject_id,
        teacher_id=teacher_id,
    )

    return lesson


def lesson_class(lesson, school_class):
    check_class = SchoolClass.query.filter_by(school_class=school_class).first()
    if check_class:
        lesson.school_classes.append(check_class)
    else:
        new_class = SchoolClass(school_class=school_class)
        db.session.add(new_class)
        db.session.commit()
        lesson.school_classes.append(new_class)
    db.session.commit()


def add_lesson(lesson_info):
    try:
        new_lesson = create_lesson(lesson_info)
        db.session.add(new_lesson)
        db.session.commit()
        if lesson_info['class']:
            for school_class in lesson_info['class']:
                lesson_class(new_lesson, school_class)
        print('Новый урок добавлен в систему.')

    except Exception as e:
        db.session.rollback()
        print(f'Ошибка при добавлении урока: {str(e)}')


# rooms = ["каб 1", "каб 2", "каб 3", "изо", "каб 5", "зал", "игровая", "кухня"]
#
# for room in rooms:
#     try:
#         new_room = Room(name=room)
#         db.session.add(new_room)
#         db.session.commit()
#
#         print('Новый кабинет добавлен в систему.')
#
#     except Exception as e:
#         db.session.rollback()
#         print(f'Ошибка при добавлении кабинета: {str(e)}')

teachers_list = [
    {'teacher': {'last_name': 'Засеева', 'first_name': 'Олеся', 'patronym': ''},
     'contact': {'telegram': '@olesyzaseeva', 'phone': '', 'other_contact': ''},
     'subjects': ['1 класс']},
    {'teacher': {'last_name': 'Земцова', 'first_name': 'Алёна', 'patronym': ''},
     'contact': {'telegram': '@zemtsova88', 'phone': '', 'other_contact': ''},
     'subjects': ['2 класс', 'Русский язык', 'Литература']},
    {'teacher': {'last_name': 'Пальчикова', 'first_name': 'Анна', 'patronym': ''},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['3 класс', '4 класс', 'Биология']},
    {'teacher': {'last_name': 'Кочанова',
                 'first_name': 'Екатерина',
                 'patronym': ''},
     'contact': {'telegram': '', 'phone': '79887326300', 'other_contact': ''},
     'subjects': ['История', 'Обществознание']},
    {'teacher': {'last_name': '?',
                 'first_name': 'Марина',
                 'patronym': 'Ростиславовна'},
     'contact': {'telegram': '', 'phone': '+79046314742', 'other_contact': ''},
     'subjects': ['Английский язык']},
    {'teacher': {'last_name': 'Чернина', 'first_name': 'Юлия', 'patronym': ''},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['Английский язык']},
    {'teacher': {'last_name': 'Лосева', 'first_name': 'Валерия', 'patronym': ''},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['Музыка']},
    {'teacher': {'last_name': 'Сапаров', 'first_name': 'Бегли', 'patronym': ''},
     'contact': {'telegram': '', 'phone': '+79775451868', 'other_contact': ''},
     'subjects': ['Информатика']},
    {'teacher': {'last_name': 'Добровольский',
                 'first_name': 'Всеволод',
                 'patronym': ''},
     'contact': {'telegram': '', 'phone': '+79062764331', 'other_contact': ''},
     'subjects': ['География']},
    {'teacher': {'last_name': 'Пылунина', 'first_name': 'Елена', 'patronym': ''},
     'contact': {'telegram': '', 'phone': '79101351169', 'other_contact': ''},
     'subjects': ['Химия']},
    {'teacher': {'last_name': 'Сергеева',
                 'first_name': 'Светлана',
                 'patronym': ''},
     'contact': {'telegram': '', 'phone': '79339335045', 'other_contact': ''},
     'subjects': ['Физкультура']},
    {'teacher': {'last_name': 'Казанцева',
                 'first_name': 'Анастасия',
                 'patronym': ''},
     'contact': {'telegram': '', 'phone': '+79120121035', 'other_contact': ''},
     'subjects': ['Математика']},
    {'teacher': {'last_name': 'Гридчин',
                 'first_name': 'Дмитрий',
                 'patronym': 'Васильевич'},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['Шахматы']},
    {'teacher': {'last_name': 'Кучерук',
                 'first_name': 'Александра',
                 'patronym': ''},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['ИЗО']},
    {'teacher': {'last_name': 'Мкервалишвили',
                 'first_name': 'Кристина',
                 'patronym': ''},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['Грузинский язык']},
    {'teacher': {'last_name': 'Водчиц',
                 'first_name': 'Ирина',
                 'patronym': 'Владимировна'},
     'contact': {'telegram': '', 'phone': '', 'other_contact': 'Нет'},
     'subjects': ['Английский язык']}
]

# existing_subjects = [subject.name for subject in Subject.query.all()]

days = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"]

# existing_subjects = [(subject.id, subject.name) for subject in Subject.query.all()]
# print(*existing_subjects, sep='\n')


# existing_rooms = [str(room.id) + ' ' + room.name for room in Room.query.all()]
# print(*existing_rooms, sep='\n')


# existing_teachers = []
# for teacher in Person.query.filter_by(teacher=True).order_by(Person.first_name).all():
#     teacher_name = teacher.first_name + ' ' + teacher.last_name
#     teacher_subjects = ', '.join([subject.name for subject in teacher.subjects_taught.all()])
#     existing_teacher = str(teacher.id) + ' | ' + teacher_name + ' | ' + teacher_subjects
#     existing_teachers.append(existing_teacher)
#
# print(*existing_teachers, sep='\n')

new_student_info = {
    "student": {
        "last_name": "Самойлова",
        "first_name": "Юлия",
        "patronym": "Михайловна",
        "dob": "10.08.2009",
        "status": "Клиент",
        "pause_until": "",
        "leaving_reason": ""
    },
    "parent": {
        1: {
            "last_name": "",
            "first_name": "",
            "patronym": ""
        }
    },
    "contact_select": {
        1: "Добавить"
    },
    "selected_contact": {
        1: ""
    },
    "contact": {
        1: {
            "telegram": "@samulya",
            "phone": "",
            "other_contact": ""
        }
    },
    "relation": {
        1: "Сам ребенок"
    },
    "primary_contact": 1
}

new_teacher_info = {
    "teacher": {
        "last_name": "Сильванская",
        "first_name": "Анна",
        "patronym": "Камильевна"
    },
    "contact": {
        "telegram": "",
        "phone": "",
        "other_contact": "Нет"
    },
    "subjects": ['3 класс']
}

teachers_dict = {
    23: ['Математика',
         'Русский язык',
         'Окружющий мир',
         'Литературное чтение',
         'Классный час'],
    24: ['Математика',
         'Литературное чтение',
         'Русский язык',
         'Литература',
         'Окружющий мир',
         'Классный час'],
    25: ['Математика',
         'Окружющий мир',
         'Биология',
         'Русский язык',
         'Литературное чтение',
         'Классный час',
         'Развивающие занятия',
         'Подготовка к школе'],
    26: ['Подготовка к школе', 'Обществознание', 'История'],
    27: ['Английский язык'],
    28: ['Английский язык', 'Английский язык взрослые'],
    29: ['Музыка'],
    30: ['Информатика'],
    31: ['География'],
    32: ['Химия'],
    33: ['Физкультура',
         'Фитнес взрослые',
         'ОФП Дошкольники',
         'ОФП Дети',
         'Классный час'],
    34: ['Математика', 'Геометрия', 'Алгебра', 'Олимпиадная математика'],
    35: ['Шахматы'],
    36: ['ИЗО'],
    37: ['Грузинский язык'],
    38: ['Английский язык'],
    39: ['Английский язык'],
    40: ['Бисероплетение'],
    41: ['Продленка', 'Робототехника'],
    42: ['Продленка', 'Тхэквондо'],
    43: ['Скорочтение'],
    44: ['Физика'],
    45: ['Мафия'],
    46: ['Математика',
         'Литературное чтение',
         'Русский язык',
         'Окружющий мир',
         'Классный час',
         'Литература']
}

lessons_list = [
 {'date': '20.11.2023',
  'start_time': '09:55',
  'end_time': '10:30',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 23,
  'class': [1]},
 {'date': '20.11.2023',
  'start_time': '10:45',
  'end_time': '11:20',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 14,
  'teacher_id': 28,
  'class': [1]},
 {'date': '20.11.2023',
  'start_time': '11:30',
  'end_time': '12:05',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 23,
  'class': [1]},
 {'date': '20.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 14,
  'teacher_id': 28,
  'class': [2, 3]},
 {'date': '20.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 24,
  'class': [2]},
 {'date': '20.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 20,
  'teacher_id': 24,
  'class': [2]},
 {'date': '20.11.2023',
  'start_time': '17:00',
  'end_time': '18:30',
  'lesson_type': 'extra',
  'room_id': 1,
  'subject_id': 12,
  'teacher_id': 26,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 46,
  'class': [3]},
 {'date': '20.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 20,
  'teacher_id': 46,
  'class': [3]},
 {'date': '20.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 14,
  'teacher_id': 39,
  'class': [3, 4]},
 {'date': '20.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 25,
  'class': [4]},
 {'date': '20.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 14,
  'teacher_id': 27,
  'class': [4]},
 {'date': '20.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 18,
  'teacher_id': 25,
  'class': [4]},
 {'date': '20.11.2023',
  'start_time': '17:00',
  'end_time': '18:30',
  'lesson_type': 'extra',
  'room_id': 2,
  'subject_id': 17,
  'teacher_id': 40,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '19:00',
  'end_time': '20:00',
  'lesson_type': 'extra',
  'room_id': 2,
  'subject_id': 5,
  'teacher_id': 37,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [6]},
 {'date': '20.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 32,
  'teacher_id': 34,
  'class': [6]},
 {'date': '20.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 23,
  'teacher_id': 25,
  'class': [6]},
 {'date': '20.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 23,
  'teacher_id': 25,
  'class': [9]},
 {'date': '20.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 36,
  'teacher_id': 34,
  'class': [9]},
 {'date': '20.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [7]},
 {'date': '20.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 35,
  'teacher_id': 34,
  'class': [7]},
 {'date': '20.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 26,
  'teacher_id': 24,
  'class': [8]},
 {'date': '20.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'individual',
  'room_id': 4,
  'subject_id': 14,
  'teacher_id': 39,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'individual',
  'room_id': 4,
  'subject_id': 32,
  'teacher_id': 34,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '15:30',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '17:30',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 14,
  'teacher_id': 39,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 32,
  'teacher_id': 46,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 25,
  'teacher_id': 46,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [8]},
 {'date': '20.11.2023',
  'start_time': '16:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 31,
  'teacher_id': 33,
  'class': [3]},
 {'date': '20.11.2023',
  'start_time': '10:00',
  'end_time': '11:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 4,
  'teacher_id': 33,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '12:15',
  'end_time': '12:50',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 31,
  'teacher_id': 33,
  'class': [1]},
 {'date': '20.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 31,
  'teacher_id': 33,
  'class': [2]},
 {'date': '20.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 31,
  'teacher_id': 33,
  'class': [4]},
 {'date': '20.11.2023',
  'start_time': '16:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 3,
  'teacher_id': 33,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '17:00',
  'end_time': '18:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 2,
  'teacher_id': 33,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '09:00',
  'end_time': '13:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 41,
  'class': []},
 {'date': '20.11.2023',
  'start_time': '13:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 42,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '09:10',
  'end_time': '09:45',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 23,
  'class': [1]},
 {'date': '21.11.2023',
  'start_time': '09:55',
  'end_time': '10:30',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 23,
  'class': [1]},
 {'date': '21.11.2023',
  'start_time': '10:45',
  'end_time': '11:20',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 18,
  'teacher_id': 23,
  'class': [1]},
 {'date': '21.11.2023',
  'start_time': '11:30',
  'end_time': '12:05',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 20,
  'teacher_id': 23,
  'class': [1]},
 {'date': '21.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 24,
  'class': [2]},
 {'date': '21.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 20,
  'teacher_id': 24,
  'class': [2]},
 {'date': '21.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [2]},
 {'date': '21.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 18,
  'teacher_id': 24,
  'class': [2]},
 {'date': '21.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 46,
  'class': [3]},
 {'date': '21.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 46,
  'class': [3]},
 {'date': '21.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 18,
  'teacher_id': 46,
  'class': [3]},
 {'date': '21.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 19,
  'teacher_id': 46,
  'class': [3]},
 {'date': '21.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 25,
  'class': [4]},
 {'date': '21.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 25,
  'class': [4]},
 {'date': '21.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 20,
  'teacher_id': 25,
  'class': [4]},
 {'date': '21.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 19,
  'teacher_id': 25,
  'class': [4]},
 {'date': '21.11.2023',
  'start_time': '17:00',
  'end_time': '18:30',
  'lesson_type': 'extra',
  'room_id': 2,
  'subject_id': 13,
  'teacher_id': 25,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [6]},
 {'date': '21.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 32,
  'teacher_id': 34,
  'class': [6]},
 {'date': '21.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 23,
  'teacher_id': 25,
  'class': [8]},
 {'date': '21.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 24,
  'teacher_id': 26,
  'class': [6]},
 {'date': '21.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 22,
  'teacher_id': 26,
  'class': [6]},
 {'date': '21.11.2023',
  'start_time': '18:00',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 21,
  'teacher_id': 28,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 36,
  'teacher_id': 34,
  'class': [7]},
 {'date': '21.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [7]},
 {'date': '21.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [9]},
 {'date': '21.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 30,
  'teacher_id': 32,
  'class': [9]},
 {'date': '21.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 35,
  'teacher_id': 34,
  'class': [9]},
 {'date': '21.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 28,
  'teacher_id': 30,
  'class': [6, 7]},
 {'date': '21.11.2023',
  'start_time': '13:55',
  'end_time': '14:55',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 11,
  'teacher_id': 43,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '15:00',
  'end_time': '16:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 15,
  'teacher_id': 35,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '16:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 15,
  'teacher_id': 35,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '17:00',
  'end_time': '18:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 9,
  'teacher_id': 41,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 30,
  'teacher_id': 32,
  'class': [8]},
 {'date': '21.11.2023',
  'start_time': '13:55',
  'end_time': '14:55',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 36,
  'teacher_id': 34,
  'class': [8]},
 {'date': '21.11.2023',
  'start_time': '15:30',
  'end_time': '16:30',
  'lesson_type': 'individual',
  'room_id': 6,
  'subject_id': 27,
  'teacher_id': 29,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '18:00',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 37,
  'teacher_id': 42,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '09:00',
  'end_time': '13:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 41,
  'class': []},
 {'date': '21.11.2023',
  'start_time': '13:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 42,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '09:10',
  'end_time': '09:45',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 23,
  'class': [1]},
 {'date': '22.11.2023',
  'start_time': '09:55',
  'end_time': '10:30',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 23,
  'class': [1]},
 {'date': '22.11.2023',
  'start_time': '10:45',
  'end_time': '11:20',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 19,
  'teacher_id': 23,
  'class': [1]},
 {'date': '22.11.2023',
  'start_time': '11:30',
  'end_time': '12:05',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 20,
  'teacher_id': 23,
  'class': [1]},
 {'date': '22.11.2023',
  'start_time': '12:15',
  'end_time': '13:00',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 7,
  'teacher_id': 34,
  'class': [1, 2]},
 {'date': '22.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 14,
  'teacher_id': 28,
  'class': [2, 3]},
 {'date': '22.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [2]},
 {'date': '22.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 24,
  'class': [2]},
 {'date': '22.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 20,
  'teacher_id': 24,
  'class': [2]},
 {'date': '22.11.2023',
  'start_time': '17:00',
  'end_time': '18:30',
  'lesson_type': 'extra',
  'room_id': 1,
  'subject_id': 12,
  'teacher_id': 25,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 46,
  'class': [3]},
 {'date': '22.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 46,
  'class': [3]},
 {'date': '22.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 18,
  'teacher_id': 46,
  'class': [3]},
 {'date': '22.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 14,
  'teacher_id': 39,
  'class': [3, 4]},
 {'date': '22.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 25,
  'class': [4]},
 {'date': '22.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 14,
  'teacher_id': 27,
  'class': [4]},
 {'date': '22.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 18,
  'teacher_id': 25,
  'class': [4]},
 {'date': '22.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 25,
  'class': [4]},
 {'date': '22.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 32,
  'teacher_id': 34,
  'class': [6]},
 {'date': '22.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 26,
  'teacher_id': 24,
  'class': [6]},
 {'date': '22.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 34,
  'teacher_id': 44,
  'class': [8]},
 {'date': '22.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 34,
  'teacher_id': 44,
  'class': [9]},
 {'date': '22.11.2023',
  'start_time': '17:00',
  'end_time': '18:30',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 10,
  'teacher_id': 45,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '11:00',
  'end_time': '12:30',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 12,
  'teacher_id': 26,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 22,
  'teacher_id': 26,
  'class': [7]},
 {'date': '22.11.2023',
  'start_time': '15:30',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '17:30',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 14,
  'teacher_id': 39,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 26,
  'teacher_id': 46,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 25,
  'teacher_id': 46,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 35,
  'teacher_id': 34,
  'class': [9]},
 {'date': '22.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 35,
  'teacher_id': 34,
  'class': [7]},
 {'date': '22.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 34,
  'teacher_id': 44,
  'class': [7]},
 {'date': '22.11.2023',
  'start_time': '17:00',
  'end_time': '18:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 9,
  'teacher_id': 41,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '11:00',
  'end_time': '12:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [8]},
 {'date': '22.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'individual',
  'room_id': 6,
  'subject_id': 14,
  'teacher_id': 39,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 24,
  'teacher_id': 26,
  'class': [8]},
 {'date': '22.11.2023',
  'start_time': '09:00',
  'end_time': '13:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 41,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '13:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 42,
  'class': []},
 {'date': '22.11.2023',
  'start_time': '15:00',
  'end_time': '16:00',
  'lesson_type': 'extra',
  'room_id': 8,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '09:55',
  'end_time': '10:30',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 23,
  'class': [1]},
 {'date': '23.11.2023',
  'start_time': '10:45',
  'end_time': '11:20',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 23,
  'class': [1]},
 {'date': '23.11.2023',
  'start_time': '11:30',
  'end_time': '12:05',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 18,
  'teacher_id': 23,
  'class': [1]},
 {'date': '23.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [2]},
 {'date': '23.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 24,
  'class': [2]},
 {'date': '23.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 18,
  'teacher_id': 24,
  'class': [2]},
 {'date': '23.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 46,
  'class': [3]},
 {'date': '23.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 46,
  'class': [3]},
 {'date': '23.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 20,
  'teacher_id': 46,
  'class': [3]},
 {'date': '23.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 25,
  'class': [4]},
 {'date': '23.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 25,
  'class': [4]},
 {'date': '23.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 20,
  'teacher_id': 25,
  'class': [4]},
 {'date': '23.11.2023',
  'start_time': '17:00',
  'end_time': '18:30',
  'lesson_type': 'extra',
  'room_id': 2,
  'subject_id': 13,
  'teacher_id': 25,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '19:00',
  'end_time': '20:00',
  'lesson_type': 'extra',
  'room_id': 2,
  'subject_id': 5,
  'teacher_id': 37,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [6]},
 {'date': '23.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 26,
  'teacher_id': 24,
  'class': [6]},
 {'date': '23.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 29,
  'teacher_id': 31,
  'class': [6]},
 {'date': '23.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 32,
  'teacher_id': 34,
  'class': [6]},
 {'date': '23.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 22,
  'teacher_id': 26,
  'class': [6]},
 {'date': '23.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 7,
  'teacher_id': 34,
  'class': [5, 6]},
 {'date': '23.11.2023',
  'start_time': '18:00',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 21,
  'teacher_id': 28,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 29,
  'teacher_id': 31,
  'class': [7]},
 {'date': '23.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 26,
  'teacher_id': 24,
  'class': [7]},
 {'date': '23.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 23,
  'teacher_id': 25,
  'class': [7]},
 {'date': '23.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'individual',
  'room_id': 4,
  'subject_id': 32,
  'teacher_id': 34,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '15:30',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '17:30',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 29,
  'teacher_id': 31,
  'class': [8]},
 {'date': '23.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 22,
  'teacher_id': 26,
  'class': [8]},
 {'date': '23.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 24,
  'teacher_id': 26,
  'class': [8]},
 {'date': '23.11.2023',
  'start_time': '15:00',
  'end_time': '16:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 15,
  'teacher_id': 35,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '16:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 15,
  'teacher_id': 35,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '17:00',
  'end_time': '18:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 9,
  'teacher_id': 41,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '11:00',
  'end_time': '12:00',
  'lesson_type': 'individual',
  'room_id': 6,
  'subject_id': 27,
  'teacher_id': 29,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '12:05',
  'end_time': '12:50',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 27,
  'teacher_id': 29,
  'class': [1, 3]},
 {'date': '23.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 27,
  'teacher_id': 29,
  'class': [2, 4]},
 {'date': '23.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 22,
  'teacher_id': 26,
  'class': [9]},
 {'date': '23.11.2023',
  'start_time': '18:00',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 37,
  'teacher_id': 42,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '09:00',
  'end_time': '13:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 41,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '13:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 42,
  'class': []},
 {'date': '23.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 8,
  'subject_id': 35,
  'teacher_id': 34,
  'class': [8]},
 {'date': '24.11.2023',
  'start_time': '09:55',
  'end_time': '10:30',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 23,
  'class': [1]},
 {'date': '24.11.2023',
  'start_time': '10:45',
  'end_time': '11:20',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 14,
  'teacher_id': 28,
  'class': [1]},
 {'date': '24.11.2023',
  'start_time': '11:30',
  'end_time': '12:05',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 20,
  'teacher_id': 23,
  'class': [1]},
 {'date': '24.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 14,
  'teacher_id': 28,
  'class': [2, 3]},
 {'date': '24.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 32,
  'teacher_id': 24,
  'class': [2]},
 {'date': '24.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [2]},
 {'date': '24.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 1,
  'subject_id': 19,
  'teacher_id': 24,
  'class': [2]},
 {'date': '24.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 46,
  'class': [3]},
 {'date': '24.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 46,
  'class': [3]},
 {'date': '24.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 20,
  'teacher_id': 46,
  'class': [3]},
 {'date': '24.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 14,
  'teacher_id': 39,
  'class': [3, 4]},
 {'date': '24.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 32,
  'teacher_id': 25,
  'class': [4]},
 {'date': '24.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 14,
  'teacher_id': 27,
  'class': [4]},
 {'date': '24.11.2023',
  'start_time': '14:55',
  'end_time': '15:40',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 25,
  'teacher_id': 25,
  'class': [4]},
 {'date': '24.11.2023',
  'start_time': '15:50',
  'end_time': '16:35',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 20,
  'teacher_id': 25,
  'class': [4]},
 {'date': '24.11.2023',
  'start_time': '16:45',
  'end_time': '17:30',
  'lesson_type': 'school',
  'room_id': 2,
  'subject_id': 7,
  'teacher_id': 34,
  'class': [3, 4]},
 {'date': '24.11.2023',
  'start_time': '09:10',
  'end_time': '09:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 25,
  'teacher_id': 24,
  'class': [6]},
 {'date': '24.11.2023',
  'start_time': '10:10',
  'end_time': '10:55',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 26,
  'teacher_id': 24,
  'class': [6]},
 {'date': '24.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 32,
  'teacher_id': 34,
  'class': [6]},
 {'date': '24.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'extra',
  'room_id': 3,
  'subject_id': 14,
  'teacher_id': 27,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '13:55',
  'end_time': '14:40',
  'lesson_type': 'school',
  'room_id': 3,
  'subject_id': 19,
  'teacher_id': 33,
  'class': [6, 7, 8, 9]},
 {'date': '24.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'school',
  'room_id': 4,
  'subject_id': 26,
  'teacher_id': 24,
  'class': [9]},
 {'date': '24.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'individual',
  'room_id': 4,
  'subject_id': 25,
  'teacher_id': 46,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '13:00',
  'end_time': '13:45',
  'lesson_type': 'individual',
  'room_id': 4,
  'subject_id': 32,
  'teacher_id': 46,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '15:30',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '17:30',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '11:05',
  'end_time': '11:50',
  'lesson_type': 'individual',
  'room_id': 5,
  'subject_id': 14,
  'teacher_id': 39,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '12:00',
  'end_time': '12:45',
  'lesson_type': 'school',
  'room_id': 5,
  'subject_id': 28,
  'teacher_id': 30,
  'class': [8, 9]},
 {'date': '24.11.2023',
  'start_time': '17:00',
  'end_time': '18:00',
  'lesson_type': 'extra',
  'room_id': 5,
  'subject_id': 9,
  'teacher_id': 41,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '10:00',
  'end_time': '11:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 4,
  'teacher_id': 33,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '12:15',
  'end_time': '12:50',
  'lesson_type': 'school',
  'room_id': 6,
  'subject_id': 31,
  'teacher_id': 33,
  'class': [1]},
 {'date': '24.11.2023',
  'start_time': '16:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 3,
  'teacher_id': 33,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '17:00',
  'end_time': '18:00',
  'lesson_type': 'extra',
  'room_id': 6,
  'subject_id': 2,
  'teacher_id': 33,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '09:00',
  'end_time': '13:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 41,
  'class': []},
 {'date': '24.11.2023',
  'start_time': '13:00',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 7,
  'subject_id': 1,
  'teacher_id': 42,
  'class': []},
 {'date': '25.11.2023',
  'start_time': '11:00',
  'end_time': '12:30',
  'lesson_type': 'extra',
  'room_id': 1,
  'subject_id': 12,
  'teacher_id': 26,
  'class': []},
 {'date': '25.11.2023',
  'start_time': '13:00',
  'end_time': '14:30',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '25.11.2023',
  'start_time': '15:30',
  'end_time': '17:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '25.11.2023',
  'start_time': '17:30',
  'end_time': '19:00',
  'lesson_type': 'extra',
  'room_id': 4,
  'subject_id': 33,
  'teacher_id': 36,
  'class': []},
 {'date': '25.11.2023',
  'start_time': '12:00',
  'end_time': '13:00',
  'lesson_type': 'individual',
  'room_id': 6,
  'subject_id': 27,
  'teacher_id': 29,
  'class': []}
]


def create_lesson_dict(lesson):
    start_time = (lesson.start_time.hour - 9) * 60 + lesson.start_time.minute
    end_time = (lesson.end_time.hour - 9) * 60 + lesson.end_time.minute

    if lesson.lesson_type == 'school':
        lesson_type = '-'.join([str(cl.school_class) for cl in lesson.school_classes.all()]) + ' класс'
    elif lesson.lesson_type == 'individual':
        lesson_type = 'индив'
    else:
        lesson_type = ''

    return {
        'time': f'{lesson.start_time.strftime("%H:%M")} - {lesson.end_time.strftime("%H:%M")}',
        'start_time': start_time,
        'end_time': end_time,
        'subject': lesson.subject_names,
        'teacher': lesson.teacher.first_name,
        'lesson_type': lesson_type,
    }


def day_lessons_list(day_room_lessons):
    lessons_for_day = []
    current_lesson = day_room_lessons[0]
    current_lesson.subject_names = [current_lesson.subject.short_name]

    for next_lesson in day_room_lessons[1:]:
        if (
                current_lesson.teacher.id == next_lesson.teacher.id
                and current_lesson.school_classes.all() == next_lesson.school_classes.all()
        ):
            current_lesson.subject_names.append(next_lesson.subject.short_name)
            current_lesson.end_time = next_lesson.end_time
        else:
            lessons_for_day.append(create_lesson_dict(current_lesson))
            next_lesson.subject_names = [next_lesson.subject.short_name]
            current_lesson = next_lesson

    lessons_for_day.append(create_lesson_dict(current_lesson))

    return lessons_for_day


def get_date(week, day_of_week):
    today = datetime.now().date()
    day_of_week_date = today - timedelta(days=today.weekday()) + timedelta(days=day_of_week) + week * timedelta(days=7)
    return day_of_week_date


def week_lessons_dict(week):
    rooms = Room.query.all()
    days_of_week = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"]
    week_lessons = {}

    for day, weekday in enumerate(days_of_week):
        lessons_date = get_date(week, day)
        lessons_date_str = lessons_date.strftime('%d.%m')
        day_lessons = {}
        for room in rooms:
            lessons_filtered = Lesson.query.filter_by(date=lessons_date, room_id=room.id).order_by(
                Lesson.start_time).all()
            day_lessons[room.name] = day_lessons_list(lessons_filtered) if lessons_filtered else []

        week_lessons[weekday] = (lessons_date_str, day_lessons)

    return week_lessons


persons_list = [
    {'id': 1, 'last_name': 'Шаповалова', 'first_name': 'Алина', 'patronym': 'Олеговна', 'dob': '12.11.2016',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 2, 'subjects': ['Бисероплетение', 'Скорочтение', 'ИЗО'], 'subjects_taught': [],
     'subscriptions': [('Бисероплетение', 8), ('Скорочтение', 1)],
     'parents': [(2, 'Мама', 'Хрипкова', 'Наталья'), (3, 'Папа', 'Шаповалов', 'Олег')], 'contacts': None,
     'balance': None},
    {'id': 2, 'last_name': 'Хрипкова', 'first_name': 'Наталья', 'patronym': 'Александровна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 2, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@khripna', '+79162956274', '599450074'), 'balance': None},
    {'id': 3, 'last_name': 'Шаповалов', 'first_name': 'Олег', 'patronym': 'Вячеславович', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 3, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('', '+79169039742', ''), 'balance': None},
    {'id': 4, 'last_name': 'Гордеев', 'first_name': 'Матвей', 'patronym': 'Сергеевич', 'dob': '05.12.2015',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 6, 'subjects': ['Шахматы', 'Английский язык', 'ИЗО'],
     'subjects_taught': [], 'subscriptions': [('Шахматы', 5), ('Английский язык', 5)],
     'parents': [(5, 'Мама', 'Хрипкова', 'Евгения'), (6, 'Папа', 'Гордеев', 'Сергей')], 'contacts': None,
     'balance': None},
    {'id': 5, 'last_name': 'Хрипкова', 'first_name': 'Евгения', 'patronym': 'Александровна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 5, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('', '+79199966403', ''), 'balance': None},
    {'id': 6, 'last_name': 'Гордеев', 'first_name': 'Сергей', 'patronym': 'Сергеевич', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 6, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@gordey', '+79259978837', ''), 'balance': None},
    {'id': 7, 'last_name': 'Ефименко', 'first_name': 'Иван', 'patronym': 'Евгеньевич', 'dob': '19.12.2015',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 8, 'subjects': ['Скорочтение', 'Английский язык', 'Мафия'],
     'subjects_taught': [], 'subscriptions': [('Скорочтение', 7), ('Английский язык', 7)],
     'parents': [(8, 'Мама', 'Ефименко', 'Мария'), (9, 'Папа', 'Ефименко', 'Евгений')], 'contacts': None,
     'balance': None},
    {'id': 8, 'last_name': 'Ефименко', 'first_name': 'Мария', 'patronym': 'Викторовна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 8, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@doctor_mary', '+79165678344', ''), 'balance': None},
    {'id': 9, 'last_name': 'Ефименко', 'first_name': 'Евгений', 'patronym': 'Владимирович', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 9, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('', '+79289405637', ''), 'balance': None},
    {'id': 10, 'last_name': 'Глушкова', 'first_name': 'Маргарита', 'patronym': 'Кирилловна', 'dob': '16.05.2016',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 11, 'subjects': ['ОФП Дети', 'Актерское мастерство', 'Бисероплетение'],
     'subjects_taught': [], 'subscriptions': [('ОФП Дети', 3)],
     'parents': [(11, 'Мама', 'Глушкова', 'Светлана'), (12, 'Папа', 'Глушков', 'Кирилл')], 'contacts': None,
     'balance': None},
    {'id': 11, 'last_name': 'Глушкова', 'first_name': 'Светлана', 'patronym': 'Юрьевна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 11, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('', '+79193576433', ''), 'balance': None},
    {'id': 12, 'last_name': 'Глушков', 'first_name': 'Кирилл', 'patronym': 'Александрович', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 12, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@glushkok', '', ''), 'balance': None},
    {'id': 13, 'last_name': 'Усачева', 'first_name': 'Кира', 'patronym': 'Михайловна', 'dob': '15.02.2012',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 14, 'subjects': ['Грузинский язык'], 'subjects_taught': [], 'subscriptions': [],
     'parents': [(14, 'Мама', 'Ржаницына', 'Софья')], 'contacts': None, 'balance': None},
    {'id': 14, 'last_name': 'Ржаницына', 'first_name': 'Софья', 'patronym': 'Дмитриевна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 14, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@Sstrazzz', '', ''), 'balance': None},
    {'id': 15, 'last_name': 'Коржавин', 'first_name': 'Артем', 'patronym': 'Михайлович', 'dob': '05.06.2010',
     'person_type': 'Ребенок', 'status': 'Лид', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 15, 'subjects': ['Программирование Scratch'], 'subjects_taught': [],
     'subscriptions': [], 'parents': [], 'contacts': ('@kor_kvant', '', ''), 'balance': None},
    {'id': 16, 'last_name': 'Иванов', 'first_name': 'Артем', 'patronym': 'Сергеевич', 'dob': '13.09.2017',
     'person_type': 'Ребенок', 'status': 'Пауза', 'teacher': False, 'leaving_reason': '', 'pause_until': '01.10.2023',
     'comment': '', 'primary_contact': 17, 'subjects': [], 'subjects_taught': [], 'subscriptions': [],
     'parents': [(17, 'Мама', 'Иванова', 'Ольга')], 'contacts': None, 'balance': None},
    {'id': 17, 'last_name': 'Иванова', 'first_name': 'Ольга', 'patronym': 'Павловна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 17, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@pavla_olga', '', ''), 'balance': None},
    {'id': 18, 'last_name': 'Петрова', 'first_name': 'Мария', 'patronym': 'Сергеевна', 'dob': '20.10.2015',
     'person_type': 'Ребенок', 'status': 'Закрыт', 'teacher': False, 'leaving_reason': 'Уехали', 'pause_until': None,
     'comment': '', 'primary_contact': 19, 'subjects': [], 'subjects_taught': [], 'subscriptions': [],
     'parents': [(19, 'Бабушка', 'Смирнова', 'Наталья')], 'contacts': None, 'balance': None},
    {'id': 19, 'last_name': 'Смирнова', 'first_name': 'Наталья', 'patronym': 'Васильевна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 19, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('', '+79167549853', ''), 'balance': None},
    {'id': 20, 'last_name': 'Шаповалова', 'first_name': 'Полина', 'patronym': 'Олеговна', 'dob': '10.08.2018',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 2, 'subjects': [], 'subjects_taught': [], 'subscriptions': [],
     'parents': [(2, 'Мама', 'Хрипкова', 'Наталья'), (3, 'Папа', 'Шаповалов', 'Олег')], 'contacts': None,
     'balance': None},
    {'id': 21, 'last_name': 'Глушкова', 'first_name': 'Екатерина', 'patronym': 'Кирилловна', 'dob': '17.02.2017',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 11, 'subjects': [], 'subjects_taught': [], 'subscriptions': [],
     'parents': [(11, 'Мама', 'Глушкова', 'Светлана'), (12, 'Папа', 'Глушков', 'Кирилл')], 'contacts': None,
     'balance': None},
    {'id': 22, 'last_name': 'Самойлова', 'first_name': 'Юлия', 'patronym': 'Михайловна', 'dob': '10.08.2009',
     'person_type': 'Ребенок', 'status': 'Клиент', 'teacher': False, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 22, 'subjects': [], 'subjects_taught': [], 'subscriptions': [], 'parents': [],
     'contacts': ('@samulya', '', ''), 'balance': None},
    {'id': 23, 'last_name': 'Засеева', 'first_name': 'Олеся', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 23,
     'subjects': [],
     'subjects_taught': ['Математика', 'Русский язык', 'Окружющий мир', 'Литературное чтение', 'Классный час'],
     'subscriptions': [], 'parents': [], 'contacts': ('@olesyzaseeva', '', ''), 'balance': None},
    {'id': 24, 'last_name': 'Земцова', 'first_name': 'Алёна', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 24,
     'subjects': [],
     'subjects_taught': ['Математика', 'Литературное чтение', 'Русский язык', 'Литература', 'Окружющий мир',
                         'Классный час'], 'subscriptions': [], 'parents': [], 'contacts': ('@zemtsova88', '', ''),
     'balance': None},
    {'id': 25, 'last_name': 'Пальчикова', 'first_name': 'Анна', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 25,
     'subjects': [],
     'subjects_taught': ['Математика', 'Окружющий мир', 'Биология', 'Русский язык', 'Литературное чтение',
                         'Классный час', 'Развивающие занятия', 'Подготовка к школе'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 26, 'last_name': 'Кочанова', 'first_name': 'Екатерина', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 26, 'subjects': [],
     'subjects_taught': ['Подготовка к школе', 'Обществознание', 'История'], 'subscriptions': [], 'parents': [],
     'contacts': ('', '79887326300', ''), 'balance': None},
    {'id': 27, 'last_name': 'Лизина', 'first_name': 'Марина', 'patronym': 'Ростиславовна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 27, 'subjects': [], 'subjects_taught': ['Английский язык'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '+79046314742', ''), 'balance': None},
    {'id': 28, 'last_name': 'Чернина', 'first_name': 'Юлия', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 28,
     'subjects': [], 'subjects_taught': ['Английский язык', 'Английский язык взрослые'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 29, 'last_name': 'Лосева', 'first_name': 'Валерия', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 29,
     'subjects': [], 'subjects_taught': ['Музыка'], 'subscriptions': [], 'parents': [], 'contacts': ('', '', 'Нет'),
     'balance': None},
    {'id': 30, 'last_name': 'Сапаров', 'first_name': 'Бегли', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 30,
     'subjects': [], 'subjects_taught': ['Информатика'], 'subscriptions': [], 'parents': [],
     'contacts': ('', '+79775451868', ''), 'balance': None},
    {'id': 31, 'last_name': 'Добровольский', 'first_name': 'Всеволод', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 31, 'subjects': [], 'subjects_taught': ['География'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '+79062764331', ''), 'balance': None},
    {'id': 32, 'last_name': 'Пылунина', 'first_name': 'Елена', 'patronym': '', 'dob': None, 'person_type': 'Взрослый',
     'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None, 'comment': '', 'primary_contact': 32,
     'subjects': [], 'subjects_taught': ['Химия'], 'subscriptions': [], 'parents': [],
     'contacts': ('', '79101351169', ''), 'balance': None},
    {'id': 33, 'last_name': 'Сергеева', 'first_name': 'Светлана', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 33, 'subjects': [],
     'subjects_taught': ['Физкультура', 'Фитнес взрослые', 'ОФП Дошкольники', 'ОФП Дети', 'Классный час'],
     'subscriptions': [], 'parents': [], 'contacts': ('', '79339335045', ''), 'balance': None},
    {'id': 34, 'last_name': 'Казанцева', 'first_name': 'Анастасия', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 34, 'subjects': [],
     'subjects_taught': ['Математика', 'Геометрия', 'Алгебра', 'Олимпиадная математика'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '+79120121035', ''), 'balance': None},
    {'id': 35, 'last_name': 'Гридчин', 'first_name': 'Дмитрий', 'patronym': 'Васильевич', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 35, 'subjects': [], 'subjects_taught': ['Шахматы'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 36, 'last_name': 'Кучерук', 'first_name': 'Александра', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 36, 'subjects': [], 'subjects_taught': ['ИЗО'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 37, 'last_name': 'Мкервалишвили', 'first_name': 'Кристина', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 37, 'subjects': [], 'subjects_taught': ['Грузинский язык'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 38, 'last_name': 'Водчиц', 'first_name': 'Ирина', 'patronym': 'Владимировна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 38, 'subjects': [], 'subjects_taught': ['Английский язык'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 39, 'last_name': 'Кузьмина', 'first_name': 'Элеонора', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 39, 'subjects': [], 'subjects_taught': ['Английский язык'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 40, 'last_name': 'Коротецкая', 'first_name': 'Алина', 'patronym': 'Леонидовна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 40, 'subjects': [], 'subjects_taught': ['Бисероплетение'], 'subscriptions': [],
     'parents': [], 'contacts': ('@alina_playschool', '', ''), 'balance': None},
    {'id': 41, 'last_name': 'Софьина', 'first_name': 'Наталья', 'patronym': 'Александровна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 41, 'subjects': [], 'subjects_taught': ['Продленка', 'Робототехника'],
     'subscriptions': [], 'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 42, 'last_name': 'Макранбекова', 'first_name': 'Фаридa', 'patronym': '', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 42, 'subjects': [], 'subjects_taught': ['Продленка', 'Тхэквондо'],
     'subscriptions': [], 'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 43, 'last_name': 'Бенина', 'first_name': 'Марина', 'patronym': 'Анатольевна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 43, 'subjects': [], 'subjects_taught': ['Скорочтение'], 'subscriptions': [],
     'parents': [], 'contacts': ('@MarinaBenina', '', ''), 'balance': None},
    {'id': 44, 'last_name': 'Афанасьев', 'first_name': 'Арсений', 'patronym': 'Михайлович', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 44, 'subjects': [], 'subjects_taught': ['Физика'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 45, 'last_name': 'Волков', 'first_name': 'Алесандр', 'patronym': 'Александрович', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 45, 'subjects': [], 'subjects_taught': ['Мафия'], 'subscriptions': [],
     'parents': [], 'contacts': ('', '', 'Нет'), 'balance': None},
    {'id': 46, 'last_name': 'Сильванская', 'first_name': 'Анна', 'patronym': 'Камильевна', 'dob': None,
     'person_type': 'Взрослый', 'status': None, 'teacher': True, 'leaving_reason': '', 'pause_until': None,
     'comment': '', 'primary_contact': 46, 'subjects': [],
     'subjects_taught': ['Математика', 'Литературное чтение', 'Русский язык', 'Окружющий мир', 'Классный час',
                         'Литература'], 'subscriptions': [], 'parents': [], 'contacts': ('', '', 'Нет'),
     'balance': None}
]
subjects_list = [
    {'id': 1, 'name': 'Продленка', 'short_name': 'Прод-ка', 'one_time_price': None, 'school_price': None,
     'subscription_types': [3, 4]},
    {'id': 2, 'name': 'ОФП Дети', 'short_name': 'ОФП Дети', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 3, 'name': 'ОФП Дошкольники', 'short_name': 'ОФП Дошк', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 4, 'name': 'Фитнес взрослые', 'short_name': 'Фитнес взр', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 5, 'name': 'Грузинский язык', 'short_name': 'Груз яз', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 6, 'name': 'Актерское мастерство', 'short_name': 'Акт маст-во', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 7, 'name': 'Олимпиадная математика', 'short_name': 'Олимп матем', 'one_time_price': 20, 'school_price': None,
     'subscription_types': []},
    {'id': 8, 'name': 'Программирование Scratch', 'short_name': 'Прогр-ие', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [1]},
    {'id': 9, 'name': 'Робототехника', 'short_name': 'Робототех', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [1]},
    {'id': 10, 'name': 'Мафия', 'short_name': 'Мафия', 'one_time_price': 10, 'school_price': None,
     'subscription_types': []},
    {'id': 11, 'name': 'Скорочтение', 'short_name': 'Скорочт', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [6]},
    {'id': 12, 'name': 'Подготовка к школе', 'short_name': 'Подг к школе', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [1, 6]},
    {'id': 13, 'name': 'Развивающие занятия', 'short_name': 'Разв зан-ия', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [1, 6]},
    {'id': 14, 'name': 'Английский язык', 'short_name': 'Англ яз', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [2]},
    {'id': 15, 'name': 'Шахматы', 'short_name': 'Шахматы', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [2]},
    {'id': 16, 'name': 'Интуитивные танцы', 'short_name': 'Инт танцы', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 17, 'name': 'Бисероплетение', 'short_name': 'Бисер', 'one_time_price': 20, 'school_price': None,
     'subscription_types': [5]},
    {'id': 18, 'name': 'Окружющий мир', 'short_name': 'Окр мир', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 19, 'name': 'Классный час', 'short_name': 'Кл час', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 20, 'name': 'Литературное чтение', 'short_name': 'Лит чтение', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 21, 'name': 'Английский язык взрослые', 'short_name': 'Англ взр', 'one_time_price': None,
     'school_price': None, 'subscription_types': [2]},
    {'id': 22, 'name': 'История', 'short_name': 'История', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 23, 'name': 'Биология', 'short_name': 'Биол', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 24, 'name': 'Обществознание', 'short_name': 'Общ-ие', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 25, 'name': 'Русский язык', 'short_name': 'Рус яз', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 26, 'name': 'Литература', 'short_name': 'Лит-ра', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 27, 'name': 'Музыка', 'short_name': 'Музыка', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 28, 'name': 'Информатика', 'short_name': 'Информ-ка', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 29, 'name': 'География', 'short_name': 'Геогр-ия', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 30, 'name': 'Химия', 'short_name': 'Химия', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 31, 'name': 'Физкультура', 'short_name': 'Физ-ра', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 32, 'name': 'Математика', 'short_name': 'Матем', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 33, 'name': 'ИЗО', 'short_name': 'ИЗО', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 34, 'name': 'Физика', 'short_name': 'Физика', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 35, 'name': 'Алгебра', 'short_name': 'Алгебра', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 36, 'name': 'Геометрия', 'short_name': 'Геом-ия', 'one_time_price': None, 'school_price': None,
     'subscription_types': []},
    {'id': 37, 'name': 'Тхэквондо', 'short_name': 'Тхэквондо', 'one_time_price': None, 'school_price': None,
     'subscription_types': [6]}
]

# for person in persons_list:
#     if person['parents']:
#         child = Person.query.filter_by(id=person['id']).first()
#         for parent in person['parents']:
#             childs_parent = Person.query.filter_by(id=parent[0]).first()
#             relation_type = parent[1]
#             relation_entry = parent_child_table.update().where(
#                 (parent_child_table.c.parent_id == childs_parent.id) &
#                 (parent_child_table.c.child_id == child.id)
#             ).values(relation=relation_type)
#             db.session.execute(relation_entry)
#             db.session.commit()

subscription_type_list = [
    {'id': 1, 'lessons': 8, 'period': None, 'duration': 40, 'price': 120},
    {'id': 2, 'lessons': 8, 'period': None, 'duration': 40, 'price': 90},
    {'id': 3, 'lessons': None, 'period': 'месяц', 'duration': None, 'price': 200},
    {'id': 4, 'lessons': None, 'period': 'час', 'duration': None, 'price': 20},
    {'id': 5, 'lessons': 8, 'period': None, 'duration': 90, 'price': 90},
    {'id': 6, 'lessons': 8, 'period': None, 'duration': 90, 'price': 120}
]

student_subscr_dict = {
    1: [('Бисероплетение', 8, 5), ('Скорочтение', 1, 6)],
    4: [('Шахматы', 5, 2), ('Английский язык', 5, 2)],
    7: [('Скорочтение', 7, 6), ('Английский язык', 7, 2)],
    10: [('ОФП Дети', 3, 1)]
}

teacher_color_list = [
    (23, 'Олеся', 'Засеева', '#C981F9'),
    (28, 'Юлия', 'Чернина', '#89F9F9'),
    (24, 'Алёна', 'Земцова', '#46BDC6'),
    (26, 'Екатерина', 'Кочанова', '#95BF83'),
    (46, 'Анна', 'Сильванская', '#76EDA6'),
    (39, 'Элеонора', 'Кузьмина', '#D0E0E3'),
    (25, 'Анна', 'Пальчикова', '#FFFFB2'),
    (27, 'Марина', 'Лизина', '#C27BA0'),
    (40, 'Алина', 'Коротецкая', '#D3EDEA'),
    (37, 'Кристина', 'Мкервалишвили', '#C6A5A9'),
    (34, 'Анастасия', 'Казанцева', '#FCC676'),
    (36, 'Александра', 'Кучерук', '#6DBA9E'),
    (33, 'Светлана', 'Сергеева', '#FF99FF'),
    (41, 'Наталья', 'Софьина', '#EA9999'),
    (42, 'Фаридa', 'Макранбекова', '#F9E9B6'),
    (32, 'Елена', 'Пылунина', '#D9F17E'),
    (30, 'Бегли', 'Сапаров', '#A8EA8A'),
    (43, 'Марина', 'Бенина', '#F9CCD2'),
    (35, 'Дмитрий', 'Гридчин', '#FF5757'),
    (29, 'Валерия', 'Лосева', '#EAD393'),
    (44, 'Арсений', 'Афанасьев', '#CEAA86'),
    (45, 'Алесандр', 'Волков', '#6D9EEB'),
    (31, 'Всеволод', 'Добровольский', '#76B4BC')
]

new_teacher_dict = {
    23: (['Математика',
          'Русский язык',
          'Окружющий мир',
          'Литературное чтение',
          'Классный час'],
         '#C981F9'),
    24: (['Математика',
          'Литературное чтение',
          'Русский язык',
          'Литература',
          'Окружющий мир',
          'Классный час'],
         '#46BDC6'),
    25: (['Математика',
          'Окружющий мир',
          'Биология',
          'Русский язык',
          'Литературное чтение',
          'Классный час',
          'Развивающие занятия',
          'Подготовка к школе'],
         '#FFFFB2'),
    26: (['Подготовка к школе', 'Обществознание', 'История'], '#95BF83'),
    27: (['Английский язык'], '#C27BA0'),
    28: (['Английский язык', 'Английский язык взрослые'], '#89F9F9'),
    29: (['Музыка'], '#EAD393'),
    30: (['Информатика'], '#A8EA8A'),
    31: (['География'], '#76B4BC'),
    32: (['Химия'], '#D9F17E'),
    33: (['Физкультура',
          'Фитнес взрослые',
          'ОФП Дошкольники',
          'ОФП Дети',
          'Классный час'],
         '#FF99FF'),
    34: (['Математика', 'Геометрия', 'Алгебра', 'Олимпиадная математика'],
         '#FCC676'),
    35: (['Шахматы'], '#FF5757'),
    36: (['ИЗО'], '#6DBA9E'),
    37: (['Грузинский язык'], '#C6A5A9'),
    38: (['Английский язык'], '#C7AAED'),
    39: (['Английский язык'], '#D0E0E3'),
    40: (['Бисероплетение'], '#D3EDEA'),
    41: (['Продленка', 'Робототехника'], '#EA9999'),
    42: (['Продленка', 'Тхэквондо'], '#F9E9B6'),
    43: (['Скорочтение'], '#F9CCD2'),
    44: (['Физика'], '#CEAA86'),
    45: (['Мафия'], '#6D9EEB'),
    46: (['Математика',
          'Литературное чтение',
          'Русский язык',
          'Окружющий мир',
          'Классный час',
          'Литература'],
         '#76EDA6')
}


# for person in persons_list:
#     if person['subjects']:
#         student = Person.query.filter_by(id=person['id']).first()
#         for subj in person['subjects']:
#             subject = Subject.query.filter_by(name=subj).first()
#             student.subjects.append(subject)
#             db.session.commit()


