"""Migration check

Revision ID: 10a34b35ccb4
Revises: ba879d809907
Create Date: 2024-10-10 21:57:56.630133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a34b35ccb4'
down_revision = 'ba879d809907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reports_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reports_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
