"""school subjects

Revision ID: 153d626af3d3
Revises: 3726826f9516
Create Date: 2024-01-19 18:29:55.905141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153d626af3d3'
down_revision = '3726826f9516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_class_table',
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_subject_class_table_class_id_school_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_class_table_subject_id_subjects'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_class_table')
    # ### end Alembic commands ###
