"""school journal

Revision ID: 1729bf7696e5
Revises: 153d626af3d3
Create Date: 2024-01-30 18:55:50.607551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1729bf7696e5'
down_revision = '153d626af3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('lesson_comment', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_school_lessons_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['persons.id'], name=op.f('fk_school_lessons_student_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_lessons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_lessons')
    # ### end Alembic commands ###
