"""finance operation type

Revision ID: 1c0a1c055460
Revises: 56a27b9bf363
Create Date: 2024-04-08 12:21:30.133826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0a1c055460'
down_revision = '56a27b9bf363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.drop_column('operation_type')

    # ### end Alembic commands ###
