"""user persons relationships

Revision ID: 1c409d833646
Revises: fb8b571e07f3
Create Date: 2024-07-26 20:41:31.845407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c409d833646'
down_revision = 'fb8b571e07f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.alter_column('price_paid',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=8, scale=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.alter_column('price_paid',
               existing_type=sa.Numeric(precision=8, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
