"""lesson_completed column

Revision ID: 22b9c24e6937
Revises: bcee8135647c
Create Date: 2023-11-23 12:17:03.383384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b9c24e6937'
down_revision = 'bcee8135647c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('lesson_completed')

    # ### end Alembic commands ###
