"""user actions

Revision ID: 38692afe0862
Revises: d5e2d43e96c0
Create Date: 2024-03-23 13:09:08.590367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38692afe0862'
down_revision = 'd5e2d43e96c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_actions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_actions')
    # ### end Alembic commands ###
