"""subject_types table

Revision ID: 4152cfecc43f
Revises: 8f0b5b442345
Create Date: 2023-11-29 12:38:27.068464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4152cfecc43f'
down_revision = '8f0b5b442345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_types'))
    )
    op.create_table('subject_types_table',
    sa.Column('subject_type_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_types_table_subject_id_subjects')),
    sa.ForeignKeyConstraint(['subject_type_id'], ['subject_types.id'], name=op.f('fk_subject_types_table_subject_type_id_subject_types'))
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lessons_lesson_type_id_subject_types'), 'subject_types', ['lesson_type_id'], ['id'])
        batch_op.drop_column('lesson_type')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('subject_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_type', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_lessons_lesson_type_id_subject_types'), type_='foreignkey')
        batch_op.drop_column('lesson_type_id')

    op.drop_table('subject_types_table')
    op.drop_table('subject_types')
    # ### end Alembic commands ###
