"""extra subject journal

Revision ID: 4c2827e7e9c8
Revises: 1c0a1c055460
Create Date: 2024-04-14 17:39:59.402263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2827e7e9c8'
down_revision = '1c0a1c055460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('lesson_time', sa.Time(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('price_paid', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('subscription_lessons', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_records_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['persons.id'], name=op.f('fk_lesson_records_student_id_persons')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lesson_records_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_records'))
    )
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_balance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.drop_column('student_balance')

    op.drop_table('lesson_records')
    # ### end Alembic commands ###
