"""balance state col in finaces

Revision ID: 506002c5072f
Revises: 5292c5b659cc
Create Date: 2024-05-27 13:06:34.449418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506002c5072f'
down_revision = '5292c5b659cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_state', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_column('balance_state')

    # ### end Alembic commands ###
