"""finance upgrade

Revision ID: 5292c5b659cc
Revises: b63df1884f3d
Create Date: 2024-04-19 12:44:47.970067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5292c5b659cc'
down_revision = 'b63df1884f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
