"""StudentAttendance table

Revision ID: 56a27b9bf363
Revises: 38692afe0862
Create Date: 2024-04-04 13:02:27.679573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a27b9bf363'
down_revision = '38692afe0862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('attending_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_student_attendances_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['persons.id'], name=op.f('fk_student_attendances_student_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_attendances'))
    )
    op.drop_table('student_lesson_attended_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_lesson_attended_table',
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), nullable=True),
    sa.Column('attending_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='fk_student_lesson_attended_table_lesson_id_lessons'),
    sa.ForeignKeyConstraint(['student_id'], ['persons.id'], name='fk_student_lesson_attended_table_student_id_persons')
    )
    op.drop_table('student_attendances')
    # ### end Alembic commands ###
