"""subject_type one-to-many

Revision ID: 729acda6806b
Revises: 5c7141a37b50
Create Date: 2023-12-07 16:53:17.950504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729acda6806b'
down_revision = '5c7141a37b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_types_table')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_subjects_subject_type_id_subject_types'), 'subject_types', ['subject_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subjects_subject_type_id_subject_types'), type_='foreignkey')
        batch_op.drop_column('subject_type_id')

    op.create_table('subject_types_table',
    sa.Column('subject_type_id', sa.INTEGER(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='fk_subject_types_table_subject_id_subjects'),
    sa.ForeignKeyConstraint(['subject_type_id'], ['subject_types.id'], name='fk_subject_types_table_subject_type_id_subject_types')
    )
    # ### end Alembic commands ###
