"""main_teacher

Revision ID: 80073c551826
Revises: c5d764d0c8d6
Create Date: 2024-02-03 13:12:42.902373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80073c551826'
down_revision = 'c5d764d0c8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_school_classes_main_teacher_id_persons', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_school_classes_main_teacher_id_persons', 'persons', ['main_teacher_id'], ['id'])

    # ### end Alembic commands ###
