"""subject_type column

Revision ID: 8f0b5b442345
Revises: 22b9c24e6937
Create Date: 2023-11-28 13:39:02.977204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0b5b442345'
down_revision = '22b9c24e6937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('subject_type')

    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
