"""final grade

Revision ID: 8f82bc858e5e
Revises: f2e85a987eb8
Create Date: 2024-02-27 19:43:42.570399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f82bc858e5e'
down_revision = 'f2e85a987eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_grade', sa.Boolean(), nullable=True))

    with op.batch_alter_table('teacher_class_table', schema=None) as batch_op:
        batch_op.drop_column('main_teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_class_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_teacher', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('school_lessons', schema=None) as batch_op:
        batch_op.drop_column('final_grade')

    # ### end Alembic commands ###
