"""finance table

Revision ID: 919baf29eb0e
Revises: 2d06177ca857
Create Date: 2024-02-08 21:58:40.609730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919baf29eb0e'
down_revision = '2d06177ca857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_finances_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finances'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance')
    # ### end Alembic commands ###
