"""lesson topic

Revision ID: 9cb2a1eec37c
Revises: 729acda6806b
Create Date: 2023-12-09 21:43:19.208153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb2a1eec37c'
down_revision = '729acda6806b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_topic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('lesson_topic')

    # ### end Alembic commands ###
