"""delete subject lesson

Revision ID: b63df1884f3d
Revises: 4c2827e7e9c8
Create Date: 2024-04-14 18:07:40.969315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63df1884f3d'
down_revision = '4c2827e7e9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_records')
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lesson_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_lessons', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_student_attendances_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_attendances_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('subscription_lessons')
        batch_op.drop_column('price_paid')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('lesson_time')
        batch_op.drop_column('date')

    op.create_table('lesson_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('lesson_time', sa.TIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('price_paid', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('subscription_lessons', sa.INTEGER(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='fk_lesson_records_lesson_id_lessons'),
    sa.ForeignKeyConstraint(['student_id'], ['persons.id'], name='fk_lesson_records_student_id_persons'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='fk_lesson_records_subject_id_subjects'),
    sa.PrimaryKeyConstraint('id', name='pk_lesson_records')
    )
    # ### end Alembic commands ###
