"""Initial migration after reorganisation

Revision ID: ba879d809907
Revises: 
Create Date: 2024-10-09 14:09:48.250807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba879d809907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=True),
    sa.Column('student_balance', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('service', sa.String(length=16), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('balance_state', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_finances_person_id_persons')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_finances_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finances'))
    )
    op.drop_table('finance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('student_balance', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('service', sa.VARCHAR(length=16), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('balance_state', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='fk_finance_person_id_persons'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='fk_finance_subject_id_subjects'),
    sa.PrimaryKeyConstraint('id', name='pk_finance')
    )
    op.drop_table('finances')
    # ### end Alembic commands ###
