"""report table, school journal

Revision ID: c5d764d0c8d6
Revises: 1729bf7696e5
Create Date: 2024-02-03 13:05:56.044764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d764d0c8d6'
down_revision = '1729bf7696e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('lesson_comment', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('grade_type', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('duty_type', sa.String(length=50), nullable=True),
    sa.Column('duty_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_reports_person_id_persons')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_reports_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_school_classes_main_teacher_id_persons'), 'persons', ['main_teacher_id'], ['id'])

    with op.batch_alter_table('school_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_school_lessons_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_school_lessons_school_class_id_school_classes'), 'school_classes', ['school_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_school_lessons_school_class_id_school_classes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_school_lessons_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('grade_type')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('school_class_id')

    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_school_classes_main_teacher_id_persons'), type_='foreignkey')
        batch_op.drop_column('main_teacher_id')

    op.drop_table('reports')
    # ### end Alembic commands ###
