"""update report

Revision ID: d26428e51941
Revises: 80073c551826
Create Date: 2024-02-06 01:52:31.636777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26428e51941'
down_revision = '80073c551826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_subject_id_subjects', type_='foreignkey')
        batch_op.drop_column('lesson_comment')
        batch_op.drop_column('grade')
        batch_op.drop_column('grade_type')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('grade_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lesson_comment', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key('fk_reports_subject_id_subjects', 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###
