"""lesson comment and split classes

Revision ID: d5e2d43e96c0
Revises: 8f82bc858e5e
Create Date: 2024-03-21 19:11:17.080934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e2d43e96c0'
down_revision = '8f82bc858e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_comment', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('split_classes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('split_classes')
        batch_op.drop_column('lesson_comment')

    # ### end Alembic commands ###
