"""subject_types description

Revision ID: e9507e240ef4
Revises: 4152cfecc43f
Create Date: 2023-11-30 18:07:57.286782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9507e240ef4'
down_revision = '4152cfecc43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_types', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
