"""subjest finance relationship

Revision ID: fb8b571e07f3
Revises: 1d72bab4454d
Create Date: 2024-06-09 17:17:35.829041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8b571e07f3'
down_revision = '1d72bab4454d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_finances_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_finances_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
